version: 2
jobs:
  build-java-8:

    working_directory: ~/cassandra-sidecar

    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:

      - checkout

      - restore_cache:
          key: cassandra-sidecar-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: cassandra-sidecar-{{ checksum "pom.xml" }}

      - run: (echo "${google_application_credentials}" > /tmp/gcp.json) && mvn -PcloudTests clean install

      - store_test_results:
          path: ~/cassandra-sidecar/target/cassandra-sidecar.jar

workflows:
  version: 2
  build:
    jobs:
      - build
